kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-dr
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: performance-extreme